import Foundation

enum ClipboardFilterDecision: Equatable, Sendable {
    case accept(String)
    case rejectProtectedType
    case rejectEmpty
    case rejectOversized
    case rejectUnsupported
}

struct ClipboardFilter: Sendable {
    static let defaultMaximumByteCount = 10 * 1_024 * 1_024

    private static let mandatoryProtectedTypeMarkers = [
        "org.nspasteboard.transienttype",
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "com.1password",
        "org.keepassxc",
        "net.antelle.keeweb"
    ]

    let maximumByteCount: Int
    let additionalProtectedTypes: Set<String>

    init(
        maximumByteCount: Int = Self.defaultMaximumByteCount,
        additionalProtectedTypes: Set<String> = []
    ) {
        self.maximumByteCount = max(1, maximumByteCount)
        self.additionalProtectedTypes = Set(additionalProtectedTypes.map { $0.lowercased() })
    }

    func evaluate(typeNames: [String], plainText: String?) -> ClipboardFilterDecision {
        let normalizedTypes = typeNames.map { $0.lowercased() }
        let hasProtectedType = normalizedTypes.contains { type in
            Self.mandatoryProtectedTypeMarkers.contains { type.contains($0) }
                || additionalProtectedTypes.contains(type)
        }
        if hasProtectedType {
            return .rejectProtectedType
        }

        guard let plainText else {
            return .rejectUnsupported
        }
        guard !plainText.isEmpty else {
            return .rejectEmpty
        }
        guard plainText.lengthOfBytes(using: .utf8) <= maximumByteCount else {
            return .rejectOversized
        }
        return .accept(plainText)
    }
}
